
version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-and-test:
    docker:
      - image: 'circleci/node:12.19.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Codecov
          command: sudo npm install -g codecov
      - run: 
          name: Test
          command: npm run test
      - run:
          name: Report Coverage
          command: npm run report-coverage
  deploy:
    docker:
      - image: 'circleci/node:12.19.0'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Serverless CLI
          command: sudo npm install -g serverless
      - run:
          name: Deploy
          command: serverless deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - feature/serverless-framework